name: Build and Test ULID Extension
on: [push, pull_request]

jobs:
  linux:
    name: Linux Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg: 17
            os: ubuntu-24.04
          - pg: 16
            os: ubuntu-24.04-arm
          - pg: 15
            os: ubuntu-22.04
          - pg: 14
            os: ubuntu-22.04-arm
          - pg: 13
            os: ubuntu-22.04
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        uses: agniswarm/pg-ext-actions/pg-setup@master
        with:
          version: ${{ matrix.pg }}
          install-contrib: 'true'
          operating-system: ${{ matrix.os }}
      
      - name: Build and test extension
        uses: agniswarm/pg-ext-actions/build-check@master
        with:
          working-directory: ./
          operating-system: ${{ matrix.os }}

  macos:
    name: macOS Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg: 17
            os: macos-15
          - pg: 14
            os: macos-13
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        uses: agniswarm/pg-ext-actions/pg-setup@master
        with:
          version: ${{ matrix.pg }}
          install-contrib: 'true'
          operating-system: ${{ matrix.os }}

      - name: "Debug PostgreSQL Installation"
        run: |
            echo "Checking pg_config availability..."
            which pg_config || echo "pg_config not in PATH"
            pg_config --version || echo "pg_config not working"
            echo "PATH: $PATH"
            echo "PG_CONFIG: $PG_CONFIG"
        shell: bash
      
      - name: Build and test extension
        uses: agniswarm/pg-ext-actions/build-check@master
        with:
          working-directory: ./
          operating-system: ${{ matrix.os }}

  windows:
    name: Windows Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg: 17
            os: windows-2025
          - pg: 14
            os: windows-2022
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        uses: agniswarm/pg-ext-actions/pg-setup@master
        with:
          version: ${{ matrix.pg }}
          install-contrib: 'true'
          operating-system: ${{ matrix.os }}
      
      - name: Build and test extension
        uses: agniswarm/pg-ext-actions/build-check@master
        with:
          working-directory: ./
          operating-system: ${{ matrix.os }}
