name: Build and Test ULID Extension
on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - postgres: 17
            os: ubuntu-24.04
          - postgres: 16
            os: ubuntu-24.04
          - postgres: 15
            os: ubuntu-22.04
          - postgres: 14
            os: ubuntu-22.04
          - postgres: 13
            os: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-${{ matrix.postgres }} postgresql-server-dev-${{ matrix.postgres }}
      
      - name: Start PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
      
      - name: Build extension
        run: |
          make clean || true
          make PG_CONFIG=/usr/bin/pg_config
        env:
          PG_CFLAGS: -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare
      
      - name: Install extension
        run: |
          sudo make PG_CONFIG=/usr/bin/pg_config install
      
      - name: Run tests
        run: |
          make PG_CONFIG=/usr/bin/pg_config installcheck
      
      - name: Show test failures
        if: failure()
        run: |
          cat regression.diffs || echo "No regression.diffs found"

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - postgres: 17
            os: macos-14
          - postgres: 16
            os: macos-14
          - postgres: 14
            os: macos-12
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install PostgreSQL
        run: |
          brew update
          brew install postgresql@${{ matrix.postgres }}
          echo "$(brew --prefix postgresql@${{ matrix.postgres }})/bin" >> $GITHUB_PATH
      
      - name: Build extension (with filtered flags)
        run: |
          make clean || true
          # Filter out problematic flags for macOS
          make PG_CONFIG=$(brew --prefix postgresql@${{ matrix.postgres }})/bin/pg_config \
            CFLAGS="-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -fvisibility=hidden -I. -I./ -I$(brew --prefix postgresql@${{ matrix.postgres }})/include/postgresql/server -I$(brew --prefix postgresql@${{ matrix.postgres }})/include/postgresql/internal"
      
      - name: Install extension
        run: |
          sudo make PG_CONFIG=$(brew --prefix postgresql@${{ matrix.postgres }})/bin/pg_config install
      
      - name: Run tests
        run: |
          make PG_CONFIG=$(brew --prefix postgresql@${{ matrix.postgres }})/bin/pg_config installcheck
      
      - name: Show test failures
        if: failure()
        run: |
          cat regression.diffs || echo "No regression.diffs found"

  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - postgres: 17
            os: windows-2022
          - postgres: 16
            os: windows-2022
          - postgres: 14
            os: windows-2022
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install PostgreSQL via Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco feature enable -n=allowGlobalConfirmation
          choco install postgresql${{ matrix.postgres }} --version=${{ matrix.postgres }}.0.0 -y --params '/SuperPassword:postgres'
          refreshenv
      
      - name: Set PGROOT environment variable
        shell: pwsh
        run: |
          $pgPath = Get-Command pg_config | Select-Object -ExpandProperty Source
          $pgDir = Split-Path (Split-Path $pgPath)
          echo "PGROOT=$pgDir" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Found PostgreSQL at: $pgDir"
      
      - name: Build with nmake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /F Makefile.win PGROOT=%PGROOT%
      
      - name: Install extension
        shell: cmd
        run: |
          nmake /F Makefile.win PGROOT=%PGROOT% install
      
      - name: Run tests
        shell: cmd
        run: |
          nmake /F Makefile.win PGROOT=%PGROOT% installcheck
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-results-${{ matrix.postgres }}
          path: |
            regression.diffs
            regression.out

  # Alternative i386 approach using direct Docker commands
  i386:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build and test in i386 container
        run: |
          docker run --platform linux/386 -it --rm \
            -v $(pwd):/src \
            -w /src \
            i386/debian:bookworm \
            sh -c "
            apt-get update && \
            apt-get install -y build-essential postgresql-16 postgresql-server-dev-16 sudo && \
            service postgresql start && \
            make && \
            make install && \
            sudo -u postgres make installcheck
            "
