name: Build and Test ULID Extension
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            pg: 19
          - os: ubuntu-24.04
            pg: 18
          - os: ubuntu-24.04
            pg: 17
          - os: ubuntu-24.04
            pg: 16
          - os: ubuntu-22.04
            pg: 15
          - os: ubuntu-22.04
            pg: 14
          - os: ubuntu-22.04
            pg: 13
          - os: macos-14
            pg: 17
          - os: macos-14
            pg: 16
          - os: macos-12
            pg: 14
          - os: windows-2022
            pg: 17
          - os: windows-2022
            pg: 16
          - os: windows-2022
            pg: 14
    
    name: PostgreSQL ${{ matrix.pg }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL
        uses: agniswarm/pg-ext-actions/pg-setup@master
        with:
          version: ${{ matrix.pg }}
          install-contrib: 'true'
      
      - name: Build and test extension
        uses: agniswarm/pg-ext-actions/build-check@master
        with:
          working-directory: ./
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-pg${{ matrix.pg }}-${{ matrix.os }}
          path: |
            regression.diffs
            regression.out
