name: Test Functionality

on:
  [push, pull_request]

jobs:
  production-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build production Docker image
      run: |
        docker build -f Dockerfile.production -t ulid-prod:test .
        
    - name: Start production container
      run: |
        docker run -d \
          --name ulid-prod-test \
          -e POSTGRES_PASSWORD=testpass \
          -e POSTGRES_DB=testdb \
          -p 5432:5432 \
          ulid-prod:test
        
        # Wait for PostgreSQL to be ready
        timeout 60 bash -c 'until docker exec ulid-prod-test pg_isready -U postgres; do sleep 2; done'
        
        # Create ULID extension
        docker exec ulid-prod-test psql -U postgres -d testdb -c "CREATE EXTENSION IF NOT EXISTS ulid;"
        
        # Verify ULID extension is available
        docker exec ulid-prod-test psql -U postgres -d testdb -c "SELECT ulid() as test_ulid;"
        
    - name: Install Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install psycopg2-binary pytest
        
    - name: Run Python tests
      run: |
        cd test/python
        PGHOST=localhost PGDATABASE=testdb PGUSER=postgres PGPASSWORD=testpass PGPORT=5432 python3 -m pytest . -v
        
    - name: Cleanup
      if: always()
      run: |
        docker stop ulid-prod-test || true
        docker rm ulid-prod-test || true
