name: valgrind
on: [push, pull_request]

jobs:
  valgrind:
    name: valgrind
    if: ${{ !startsWith(github.ref_name, 'mac') && !startsWith(github.ref_name, 'windows') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Postgres (valgrind)
        uses: ankane/setup-postgres-valgrind@v1
        with:
          postgres-version: 17
          check-ub: yes

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build static Go binary for valgrind
        env:
          CGO_ENABLED: "0"
        run: |
          echo "Building static Go binary for valgrind (CGO_ENABLED=$CGO_ENABLED)"
          # Build using the Makefile (keeps parity with other jobs)
          make OPTFLAGS=""

      - name: Install preserving PG_CONFIG (install-local)
        run: |
          export PG_CONFIG=$(which pg_config)
          echo "Using PG_CONFIG=$PG_CONFIG"
          sudo --preserve-env=PG_CONFIG make install-local

      - name: Run installcheck under valgrind (with optional suppressions)
        run: |
          set -euo pipefail
          SUPP="scripts/valgrind/supress-go.supp"
          if [ -f "$SUPP" ]; then
            echo "Found suppression file: $SUPP"
            valgrind --trace-children=yes \
              --suppressions="$SUPP" \
              --leak-check=full --show-leak-kinds=all \
              --error-exitcode=1 \
              make installcheck
          else
            echo "No suppression file found at $SUPP; running valgrind without suppressions"
            valgrind --trace-children=yes \
              --leak-check=full --show-leak-kinds=all \
              --error-exitcode=1 \
              make installcheck
          fi
